import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../../../styles/Home.module.css'
import DashboardNav from '../../../components/DashboardNav'
import FlagCalendar from '../../../components/FlagCalendar'
import { useState, useEffect } from 'react'
import { FlagSet } from '../../../mirage/models'

const FlagsHome: NextPage = () => {
  const [recentFlags, setRecentFlags] = useState<FlagSet[] | []>([]);

  useEffect(() => {
    fetch("/api/flags/flagsets")
    .then((res) => res.json())
    .then((json) => {
      setRecentFlags(json.flagSets);
    })
  }, [])

  return (
    <div>
      <Head>
        <title>Flag Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className={`${styles.primary_nav}`}>
          <Link href="/teachers/flags/#"><a>Profile</a></Link>
          <Link href="/"><a>Log Out</a></Link>
        </nav>
      </header>
      <main className={`${styles.flex} ${styles.dashboard}`}>
        <DashboardNav></DashboardNav>
        <section className={`${styles.dashboard_content}`}>
          <h1>Welcome Back, Teacher Mark</h1>
          <FlagCalendar></FlagCalendar>   
          <div className={`${styles.flex} ${styles.flex_between} ${styles.flex_grow} ${styles.flex_gap}`}>
            {/* <FlagList></FlagList> */}
            <article className={`${styles.card}`}>
              <h2>Recent Flags</h2>
              <ul>
                {recentFlags?.map((flag: FlagSet) => (
                  <li key={`flag-${flag.id}`} className={`${styles.flex} ${styles.flex_between}`}>
                    {flag.title} Tiles: {flag.flagSetTile.length}
                    <div className={`${styles.flex} ${styles.flex_gap}`}>
                      <Link href={`./flags/play/${flag.id}`}><a>Play</a></Link>
                      <Link href={`./flags/edit/${flag.id}`}><a>Edit</a></Link>
                    </div> 
                  </li>
                ))}
              </ul>
            </article>
            <article className={`${styles.card}`}>
              <div className={`${styles.dashboard_image_container}`}>
                <Image 
                  className={styles.stacked_img}
                  src="/images/flags_ui_screenshot.jpg"
                  layout='fill'
                  objectFit='cover'
                  alt="An image of a flagboard"
                 />
              </div>
                <h2>
                  <Link href="flags/create"><a>Create</a></Link>
                </h2>
            </article>
            <article className={`${styles.card}`}>
              <h2>
                <Link href="#"><a>All Teacher&apos;s Flags</a></Link>
              </h2>
            </article>
          </div>
        </section>
      </main>
    </div>
  )
}

export default FlagsHome
