import { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../../../styles/Home.module.css'
import FlagBoard from '../../../components/FlagBoard'

export default function PlayFlags() {
    return (
    <div>
        <Head>
        <title>Play Flags</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link 
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Poppins"
        >
        </link>
        <link 
          rel="stylesheet" 
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
        </Head>
        <header style={{ position: 'fixed', width: '100vw', background: '#58C3FF', display: 'flex', justifyContent: 'right', padding: '1rem'}}>
        {/* <nav style={{ backgroundColor: '#58C3FF', color: 'white'}}> 
            <Link href="/"><a>Log Out</a></Link>
            <Link href="/teachers"><a>Dashboard</a></Link>
            <Link href="/teachers/flags"><a>Flags</a></Link>
        </nav> */}
            <Link href="/teachers/flags">
                <a>
                    <span 
                    className="material-symbols-outlined"
                    style={{ color: 'white', fontSize: '3rem'}}
                    >
                        arrow_back
                    </span>
                </a>
            </Link>
        
        </header>
        <main>
            <FlagBoard></FlagBoard>
        </main>
    </div>
    )
}