import { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../../../styles/Home.module.css'
import FlagBoard from '../../../components/FlagBoard'

export default function PlayFlags() {
    return (
    <div>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Poppins"></link>
        </Head>
        <header>
        <nav>
            <Link href="/"><a>Log Out</a></Link>
            <Link href="/teachers"><a>Dashboard</a></Link>
            <Link href="/teachers/flags"><a>Flags</a></Link>
        </nav>
        </header>
        <main>
            <FlagBoard></FlagBoard>
        </main>
    </div>
    )
}