import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../../../styles/Home.module.css'

const Home: NextPage = () => {
    const flags = [
        {
            image: "https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ae.svg",
            country: "United Arab Emirates",
            id: 1
        },
    ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <Link href="/"><a>Log Out</a></Link>
          <Link href="/teachers"><a>Dashboard</a></Link>
          <Link href="/teachers/flags"><a>Flags</a></Link>
        </nav>
      </header>
      <main className={styles.main}>
        <h1>Your Flags</h1>
        <p>Time to play!</p>
        <div className={styles.flags}>
            {flags.forEach(flag => {
                return (
                    <div key={flag.id}>
                        <Image
                            src={flag.image}
                            height={150}
                            width={200}
                        />
                        <p>{flag.country}</p>
                    </div>
                );
            })}
        </div>
      </main>
    </div>
  )
}

export default Home
