import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'
import DashboardNav from '../../components/DashboardNav'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
  const router = useRouter()
  console.log(router);

  return (
    <div className={styles.container}>
      <Head>
        <title>Mario</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className={`${styles.primary_nav}`}>
          <Link href="/"><a>Logout</a></Link>
        </nav>
      </header>
      <main className={`${styles.flex} ${styles.dashboard}`}>
        <DashboardNav></DashboardNav>
        <section className={`${styles.flex} ${styles.flex_column}`}>
          <h1>Welcome back, Teacher Teacher!</h1>
          <p>This is your main dashboard. Keep track of everything you need to do today and throughout the week.</p>
          <p>Today&apos;s schedule</p>
          <p>Absent Today</p>
          <p>Flags</p>
          <p>Flags</p>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
