import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from '../../../../styles/Home.module.css'
import DashboardNav from '../../../../components/DashboardNav'
import DeleteModal from '../../../../components/edit/DeleteModal'
import { useRouter } from "next/router";
import { useEffect, useState, useRef } from "react";
import { IFlagSet, IFlagsetQuestion } from "../../../../interfaces";

export default function EditFlagset() {
    const router = useRouter()
    
    const [selectedFlag, setSelectedFlag] = useState<IFlagSet | undefined>(undefined);
    const [isDeleteModalVisible, setIsDeleteModalVisible] = useState<boolean>(false);
    const [hasFlagsetQuestions, setHasFlagsetQuestions] = useState<boolean>(false);
    const [flagsetQuestions, setFlagsetQuestions] = useState<[]>([]);
    
    const deleteModal = useRef<HTMLDialogElement>(null)
    

    async function getSelectedFlag(flagId: string | string[] | undefined) {
        console.log(flagId);
        try {
            await fetch(`/api/flags/flagsets/${flagId}`)
            .then((res) => res.json())
            .then((json) => {
                console.log(json.flagset);
                console.log(json.flagset.flagsetQuestions);
                console.log(json.flagset.flagsetQuestions.length);
                setSelectedFlag(json.flagset);
                if(json.flagset.flagsetQuestions.length > 0) {
                    setHasFlagsetQuestions(true);
                }
                setFlagsetQuestions(json.flagset.flagsetQuestions);
            })
        } catch(e) {
            console.log(e);
        }
    }

    function updateFlagDetails() {
        // TODO: function for patch 
        // or put to update this ID, and call 
        // the updated one, and setSelectedFlag
    }

    function openDeleteModal() {
        deleteModal?.current?.showModal();
    }

    function deleteFlagSet() {
        fetch(`/api/flagsets/delete/${selectedFlag?.id}`, {method: 'DELETE'});
        router.push('/teachers/flags');
    }

    function cancelDelete() {
        deleteModal?.current?.close();
    }

    useEffect(() => {
        if (router.isReady) {
            console.log('router is ready')
            console.log(router.query.id)
            getSelectedFlag(router.query.id);
        }
    }, [router.isReady, router.query.id])

    return (
        <>
            <div>
                <Head>
                    <title>Create Flags</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <header>
                    <nav className={`${styles.primary_nav}`}>
                        <Link href="/teachers/flags/#"><a>Profile</a></Link>
                        <Link href="/"><a>Log Out</a></Link>
                    </nav>
                </header>
                <main className={`${styles.dashboard}`}>
                    {/* {isDeleteModalVisible && (
                        <DeleteModal id={selectedFlag?.id}
                        ></DeleteModal>
                    )} */}
                    <dialog
                        ref={deleteModal}
                    >
                        <div style={{marginBottom: '1rem',}}>
                            <p style={{textAlign: 'center', fontWeight: '700'}}>Warning!</p>
                            <p>You are about to delete your flag set: {selectedFlag?.title}.</p>
                            <p>Once you do, you can&apos;t get it back.</p>
                        </div>
                        <p style={{marginBottom: '1rem',}}>Are you sure you want to delete this set?</p>
                        <div style={{display: 'flex', justifyContent: 'center', gap: '1rem',}}>
                            <button className={styles.delete_button}onClick={deleteFlagSet}>Delete</button>
                            <button className={styles.button} onClick={cancelDelete}>Cancel</button>
                        </div>
                    </dialog>
                    <div className={`${styles.dashboard_content_wrapper}`}>
                        <DashboardNav></DashboardNav>
                        {!selectedFlag && (
                        <div style={{ padding: '1rem', width: 'min(100%, 1200px)', minHeight: '70vh'}}>
                            <div style={{minHeight: '70vh', padding: '1rem', background: 'white'}}>
                                <h1>Loading...</h1>
                            </div>
                        </div>
                        )}
                        <div style={{ padding: '1rem', width: 'min(100%, 1200px)', minHeight: '70vh'}}>
                            <div style={{minHeight: '70vh', padding: '1rem', background: 'white'}}>
                        {selectedFlag && (
                            <>
                                <div className={`${styles.flex} ${styles.flex_between}`}>
                                    <h1>{selectedFlag.title}</h1>
                                    {/* <button 
                                        className={styles.delete_button}
                                        onClick={otherOpenDeleteModal}
                                    >Modal Delete</button> */}
                                    <button 
                                        className={styles.delete_button}
                                        onClick={openDeleteModal}
                                    >Delete</button>
                                </div>
                                <hr></hr>
                                <section>
                                    <table>
                                        <thead>
                                            <tr>
                                                <th></th>
                                                <th>Current</th>
                                                <th>New</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Level</td>
                                                <td>
                                                <input 
                                                style={{textAlign: 'right',}}
                                                placeholder={selectedFlag.level ? selectedFlag.level : '1'}></input>
                                                </td>
                                                <td>
                                                <input 
                                                style={{textAlign: 'right',}}
                                                type='number'></input>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Week</td>
                                                <td>
                                                <input 
                                                style={{textAlign: 'right',}}
                                                placeholder={selectedFlag.week ? selectedFlag.week : '1'}></input>
                                                </td>
                                                <td>
                                                <input 
                                                style={{textAlign: 'right',}}
                                                type='number'></input>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Date</td>
                                                <td>
                                                <input 
                                                style={{textAlign: 'right',}}
                                                placeholder={selectedFlag.date}></input>
                                                </td>
                                                <td>
                                                <input 
                                                style={{textAlign: 'right',}}
                                                type='date'></input>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <button onClick={updateFlagDetails}>Save</button>
                                </section>
                                </>
                        )}
                        {hasFlagsetQuestions? (
                            flagsetQuestions.map((question: IFlagsetQuestion) => (
                                <article 
                                    key={`fs-q-${question.id}`} 
                                    className={styles.question_front_back_container}
                                >
                                    <div style={{ position: 'relative', width: '30%'}}>
                                        <h3 style={{ textAlign: 'center' }}>Front Side</h3>
                                        <div style={{ position: 'relative', width: '100%', aspectRatio: '4 / 3'}}>
                                            <Image
                                                alt={`A picture of the ${question.country} flag`}
                                                src={question.flag}
                                                layout='fill'
                                                objectFit="cover"
                                            ></Image>
                                        </div>
                                    </div>
                                    <div style={{ width: '70%'}}>
                                        <h3 style={{ textAlign: 'center' }}>Back Side</h3>
                                    </div>
                                </article>
                            ))
                        ) : (
                            <p>False</p>
                        )}
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </>
    );
}