import Head from "next/head";
import Link from "next/link";
import styles from '../../../../styles/Home.module.css'
import DashboardNav from '../../../../components/DashboardNav'
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { IFlagSet } from "../../../../interfaces";

export default function EditFlagset() {
    const flagId = useRouter().query.id;
    const [selectedFlag, setSelectedFlag] = useState<IFlagSet | undefined>(undefined);

    async function getSelectedFlag() {
        try {
            await fetch(`/api/flags/flagsets/${flagId}`)
            .then((res) => res.json())
            .then((json) => {
                setSelectedFlag(json.flagset);
            })
        } catch(e) {
            console.log(e);
        }
    }

    function updateFlagDetails() {
        // TODO: function for patch 
        // or put to update this ID, and call 
        // the updated one, and setSelectedFlag

    }
    useEffect(() => {
        getSelectedFlag();
    }, []);
    return (
        <>
            <div>
                <Head>
                    <title>Create Flags</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <header>
                    <nav className={`${styles.primary_nav}`}>
                        <Link href="/teachers/flags/#"><a>Profile</a></Link>
                        <Link href="/"><a>Log Out</a></Link>
                    </nav>
                </header>
                <main className={`${styles.dashboard}`}>
                    <div className={`${styles.dashboard_content_wrapper}`}>
                        <DashboardNav></DashboardNav>
                        {!selectedFlag && (
                        <div style={{ padding: '1rem', width: 'min(100%, 1200px)', minHeight: '70vh'}}>
                            <div style={{minHeight: '70vh', padding: '1rem', background: 'white'}}>
                                <h1>Loading...</h1>
                            </div>
                        </div>
                        )}
                        {selectedFlag && (
                        <div style={{ padding: '1rem', width: 'min(100%, 1200px)', minHeight: '70vh'}}>
                            <div style={{minHeight: '70vh', padding: '1rem', background: 'white'}}>
                                <h1>{selectedFlag.title}</h1>
                                <hr></hr>
                                <section>
                                    <table>
                                        <thead>
                                            <tr>
                                                <th></th>
                                                <th>Current</th>
                                                <th>New</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Level</td>
                                                <td>
                                                <input 
                                                style={{textAlign: 'right',}}
                                                placeholder={selectedFlag.level ? selectedFlag.level : '1'}></input>
                                                </td>
                                                <td>
                                                <input 
                                                style={{textAlign: 'right',}}
                                                type='number'></input>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Week</td>
                                                <td>
                                                <input 
                                                style={{textAlign: 'right',}}
                                                placeholder={selectedFlag.week ? selectedFlag.week : '1'}></input>
                                                </td>
                                                <td>
                                                <input 
                                                style={{textAlign: 'right',}}
                                                type='number'></input>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Date</td>
                                                <td>
                                                <input 
                                                style={{textAlign: 'right',}}
                                                placeholder={selectedFlag.date}></input>
                                                </td>
                                                <td>
                                                <input 
                                                style={{textAlign: 'right',}}
                                                type='date'></input>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <button onClick={updateFlagDetails}>Save</button>
                                </section>
                                <section>
                                    <h2>Edit the Flags here</h2>
                                </section>
                                <section>
                                    <h2>Edit the questions for each flag here</h2>
                                </section>
                            </div>
                        </div>
                        )}
                    </div>
                </main>
            </div>
        </>
    );
}