import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sky Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header style={{position: 'fixed', width: '100%'}}>
        <nav className={`${styles.primary_nav}`}>
          <Link href="/"><a>Home</a></Link>
        </nav>
      </header>
      <main className={`${styles.flex} ${styles.flex_center}`}>
        <div className={styles.form_margin}style={{ border: '1px solid black', borderRadius: '5px', padding: '5rem',}}>
          <h1 style={{ textAlign: 'center',}}>Log In</h1>
          <p>This page will eventually be the log in page. You can just click &apos;Go!&apos; for now.</p>
          <form className={styles.form_margin}>
            <div className={`${styles.form_group}`}>
              <label>Email</label>
              <input type="text" />
            </div>
            <div className={`${styles.flex_column} ${styles.form_group}`}>
              <label>Password</label>
              <input type="text" />
            </div>
            <div className={`${styles.form_button_group}`}>
              <Link href="/mario"><a className={styles.form_button}>Mario</a></Link>
              <Link href="/admin"><a className={styles.form_button}>Admin</a></Link>
              <Link href="/teachers"><a className={styles.form_button}>Teachers</a></Link>
            </div>
          </form>
        </div>
      </main>
    </div>
  )
}

export default Home
